export const adminLayoutCopy = {
    'pt-BR': {
        languageLabel: 'Idioma',
        languagePortuguese: 'Português',
        languageEnglish: 'Inglês',
        moduleNavigation: 'Navegação do módulo',
        generalAccess: 'Acesso geral',
        profile: 'Perfil',
        roleUser: 'Usuário',
        roleAdmin: 'Admin',
        openMenu: 'Abrir menu',
        closeMenu: 'Fechar menu',
        expandMenu: 'Expandir menu',
        collapseMenu: 'Minimizar menu',
        logout: 'Sair',
        pendingChanges: ' • alterações pendentes',
        quickNavigationTitle: 'Navegação rápida',
        quickNavigationDescription: 'Digite um número para navegar:',
        quickNavigationPlaceholder: 'Digite 1-7',
        shortcutsLegend:
            'Atalhos globais: Ctrl+S (salvar), Alt+Shift+1..3 (salvar perfil), Alt+1..3 (aplicar perfil), ESC (fechar).',
        panelHome: 'Painel Principal',
        panelRegistry: 'Painel de Cadastro',
        panelPayroll: 'Painel de Pagamentos',
        panelVacations: 'Painel Controle de Férias',
        panelFreight: 'Central de Fretes',
        panelProgramming: 'Painel de Programação',
        panelFines: 'Painel de Gestão de Multas',
        panelInterviews: 'Painel de Entrevistas',
        quickInterviews: 'Entrevistas',
        quickPayroll: 'Pagamentos',
        quickVacations: 'Férias',
        quickRegistry: 'Cadastro',
        quickFreight: 'Gestão de Fretes',
        quickProgramming: 'Programação',
        quickFines: 'Gestão de Multas',
        linkDashboard: 'Dashboard',
        linkInterviews: 'Entrevistas',
        linkCurriculums: 'Currículos',
        linkCandidateList: 'Lista de candidatos',
        linkNewInterview: 'Nova entrevista',
        linkNextSteps: 'Próximos Passos',
        linkOnboarding: 'Onboarding',
        linkProgrammingDashboard: 'Programação de Viagens',
        linkCollaborators: 'Colaboradores',
        linkUnits: 'Unidades',
        linkUsers: 'Usuários',
        linkFunctions: 'Funções',
        linkPaymentTypes: 'Tipo de Pagamentos',
        linkPlatesAviaries: 'Placas e Aviários',
        linkInfractions: 'Infrações',
        linkLaunchPayments: 'Lançar Pagamentos',
        linkPaymentList: 'Lista de Pagamentos',
        linkPendingExtras: 'Diárias e Extras',
        linkDiscounts: 'Descontos',
        linkUnitReport: 'Relatório por Unidade',
        linkCollaboratorReport: 'Relatório por Colaborador',
        linkVacationList: 'Lista de Férias',
        linkLaunchVacation: 'Lançar Férias',
        linkLaunchFreight: 'Lançar Fretes',
        linkFreightList: 'Lista de Fretes',
        linkSpotFreight: 'Lançar Fretes Spot',
        linkDisplacements: 'Deslocamentos e Pendências',
        linkCanceledLoads: 'Cargas Canceladas',
        linkFleetMonthly: 'Frota mensal',
        linkAnalyticsHub: 'Central Analítica',
        linkFinesDashboard: 'Dashboard de Multas',
        linkFinesLaunch: 'Lançar Multas',
        linkFinesLaunchNotification: 'Lançar Notificação',
        linkFinesList: 'Lista de Multas',
        linkExecutive: 'Dashboard Executivo',
        linkPending: 'Pendências',
        linkSettings: 'Configurações',
        linkLog: 'Log',
        menuSearchPlaceholder: 'Buscar no menu',
        menuSearchNoResults: 'Nenhum item encontrado para este termo.',
        quickSearchPlaceholder:
            'Buscar por colaborador, placa, viagem, multa...',
        quickSearchTitle: 'Busca global',
        quickSearchEmpty: 'Digite pelo menos 2 caracteres para buscar.',
        quickSearchNoResults: 'Nenhum resultado encontrado para este termo.',
        quickSearchRecentTitle: 'Atalhos favoritados',
        quickSearchRecentEmpty: 'Nenhum atalho favoritado ainda.',
        quickSearchPin: 'Favoritar atalho',
        quickSearchUnpin: 'Remover favorito',
        quickSearchPinned: 'Atalho salvo com sucesso.',
        quickSearchUnpinned: 'Atalho removido com sucesso.',
        quickSearchOpen: 'Abrir',
    },
    'en-US': {
        languageLabel: 'Language',
        languagePortuguese: 'Portuguese',
        languageEnglish: 'English',
        moduleNavigation: 'Module navigation',
        generalAccess: 'General access',
        profile: 'Profile',
        roleUser: 'User',
        roleAdmin: 'Admin',
        openMenu: 'Open menu',
        closeMenu: 'Close menu',
        expandMenu: 'Expand menu',
        collapseMenu: 'Collapse menu',
        logout: 'Log out',
        pendingChanges: ' • pending changes',
        quickNavigationTitle: 'Quick navigation',
        quickNavigationDescription: 'Type a number to navigate:',
        quickNavigationPlaceholder: 'Type 1-7',
        shortcutsLegend:
            'Global shortcuts: Ctrl+S (save), Alt+Shift+1..3 (save profile), Alt+1..3 (apply profile), ESC (close).',
        panelHome: 'Main panel',
        panelRegistry: 'Registry panel',
        panelPayroll: 'Payroll panel',
        panelVacations: 'Vacation control panel',
        panelFreight: 'Freight hub',
        panelProgramming: 'Programming panel',
        panelFines: 'Fines management panel',
        panelInterviews: 'Interviews panel',
        quickInterviews: 'Interviews',
        quickPayroll: 'Payroll',
        quickVacations: 'Vacations',
        quickRegistry: 'Registry',
        quickFreight: 'Freight management',
        quickProgramming: 'Programming',
        quickFines: 'Fines management',
        linkDashboard: 'Dashboard',
        linkInterviews: 'Interviews',
        linkCurriculums: 'Resumes',
        linkCandidateList: 'Candidate list',
        linkNewInterview: 'New interview',
        linkNextSteps: 'Next steps',
        linkOnboarding: 'Onboarding',
        linkProgrammingDashboard: 'Trip scheduling',
        linkCollaborators: 'Collaborators',
        linkUnits: 'Units',
        linkUsers: 'Users',
        linkFunctions: 'Functions',
        linkPaymentTypes: 'Payment types',
        linkPlatesAviaries: 'Plates and aviaries',
        linkInfractions: 'Infractions',
        linkLaunchPayments: 'Launch payroll',
        linkPaymentList: 'Payroll list',
        linkPendingExtras: 'Daily pay and extras',
        linkDiscounts: 'Deductions',
        linkUnitReport: 'Unit report',
        linkCollaboratorReport: 'Collaborator report',
        linkVacationList: 'Vacation list',
        linkLaunchVacation: 'Launch vacation',
        linkLaunchFreight: 'Launch freight',
        linkFreightList: 'Freight list',
        linkSpotFreight: 'Launch spot freight',
        linkDisplacements: 'Displacements and issues',
        linkCanceledLoads: 'Canceled loads',
        linkFleetMonthly: 'Monthly fleet',
        linkAnalyticsHub: 'Analytics hub',
        linkFinesDashboard: 'Fines dashboard',
        linkFinesLaunch: 'Launch fines',
        linkFinesLaunchNotification: 'Launch notification',
        linkFinesList: 'Fines list',
        linkExecutive: 'Executive dashboard',
        linkPending: 'Pending items',
        linkSettings: 'Settings',
        linkLog: 'Log',
        menuSearchPlaceholder: 'Search menu',
        menuSearchNoResults: 'No navigation items found for this term.',
        quickSearchPlaceholder: 'Search collaborator, plate, trip, fine...',
        quickSearchTitle: 'Global search',
        quickSearchEmpty: 'Type at least 2 characters to search.',
        quickSearchNoResults: 'No results found for this term.',
        quickSearchRecentTitle: 'Pinned shortcuts',
        quickSearchRecentEmpty: 'No pinned shortcuts yet.',
        quickSearchPin: 'Pin shortcut',
        quickSearchUnpin: 'Unpin shortcut',
        quickSearchPinned: 'Shortcut pinned successfully.',
        quickSearchUnpinned: 'Shortcut removed successfully.',
        quickSearchOpen: 'Open',
    },
} as const;
